---
# global settings
main_username: kurt
main_groupname: '{{ main_username }}'
main_email: '{{ secrets_main_email }}'
main_emailpw: '{{ secrets_main_emailpw }}'
main_sambapw: '{{ secrets_main_sambapw }}'
main_uid: '1000'
main_gid: '{{ main_uid }}'
disckey: '{{ secrets_disckey }}'

# grog.package
# common package list - override in group/host vars
# should I do it this way? i.e. it will just merge + uniqify
package_list:
  - name: build-essential
  - name: curl
  - name: git
  - name: htop
  - name: net-tools
  - name: python3
  - name: rsync
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# geerlingguy.ntp
ntp_timezone: 'America/New_York'
# ntp_area:'North America'  to limit pool to use closer servers?
# ntp_manage_config: true

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: 'no'
security_ssh_permit_root_login: 'no'
security_ssh_usedns: 'no'
security_autoupdate_enabled: true
security_fail2ban_enabled: true
security_sudoers_passwordless:
  - '{{main_username}}'

# geerlingguy.docker
docker_install_compose: true
# default version: docker_compose_version: "1.26.0"
# current V1 latest (must be V1 if using community.docker.docker_compose):
docker_compose_version: '1.29.2'
# default = docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
# default = docker_compose_path: /usr/local/bin/docker-compose
docker_users:
  - '{{ main_username }}'
# what did I set this to???  I think just log options
# docker_daemon_options:
#   log-opts:
#    max-size: "100m"

# ironicbadger.docker_compose_generator
appdata_path: /mnt/storage/appdata
global_env_vars:
  - 'PUID={{ main_uid }}'
  - 'PGID={{ main_gid }}'
  - 'TZ={{ ntp_timezone }}'
  - UMASK=<027>
docker_compose_generator_uid: '{{ main_uid }}'
docker_compose_generator_gid: '{{ main_gid }}'
docker_compose_generator_user: '{{ main_username }}'
docker_compose_generator_output_path: /home/{{ main_username }}/compose
