---
myhostname: mummy

# grog.package - extra packages for this group/server
package_list_group:
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: smartmontools
  - name: cryptsetup
  - name: zfsutils-linux

## snapraid
snapraid_config_excludes:
  - '*.unrecoverable'
  - '/tmp/'
  - '/lost+found/'
  - 'downloads/'
  - '*.!sync'
  - '.AppleDouble'
  - '._AppleDouble'
  - '.DS_Store'
  - '._.DS_Store'
  - '.Thumbs.db'
  - '.fseventsd'
  - '.Spotlight-V100'
  - '.TemporaryItems'
  - '.Trashes'
  - '.AppleDB'

mummy_main_storage_path: /mnt/storage
extra_mountpoints:
  - { path: '{{ mummy_main_storage_path }}' }

# shutterkurt-mergerfs role
# insert mergerfs item into fstab
mergerfs_fstab_info:
  - {
      source: '/mnt/dat*:/mnt/tank/docs-shared:/mnt/tank/photo-wip',
      mountpoint: '/mnt/storage',
      fs: fuse.mergerfs,
      opts: 'defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,cache.files=off,dropcacheonclose=true,minfreespace=20G,fsname=mergerfs',
    }
# install or not the extra python tools with mergerfs
mergerfs_tools_install: true

# ironicbadger-snapraid
# also used in setting up disks - fstab and crypttab
snapraid_runner: true
snapraid_parity_disks:
  - {
      name: par1,
      path: /mnt/par1,
      device: 'UUID=dontKnowYet',
      fs: ext4,
      fsopts: defaults,
      cryptopts: luks,
      content: false,
    }

snapraid_data_disks:
  - {
      name: dat1,
      path: /mnt/dat1,
      device: 'UUID=b9ab9d04-1fb5-4172-9ccc-62ab639efef1',
      fs: ext4,
      fsopts: defaults,
      cryptopts: luks,
      content: true,
    }
  - {
      name: dat2,
      path: /mnt/dat2,
      device: 'UUID=52037777-302f-4bf0-93bf-9d036e92de1f',
      fs: ext4,
      fsopts: defaults,
      cryptopts: luks,
      content: true,
    }
  - {
      name: dat3,
      path: /mnt/dat3,
      device: 'UUID=c9a937ba-96b5-4cf5-841e-e209996e47aa',
      fs: ext4,
      fsopts: defaults,
      cryptopts: luks,
      content: true,
    }
  - {
      name: dat4,
      path: /mnt/dat4,
      device: 'UUID=2a7cbd31-8cbe-411a-926d-6c841ea69f07',
      fs: ext4,
      fsopts: defaults,
      cryptopts: luks,
      content: true,
    }

filesharing_shares:
  - {
      name: storage,
      comment: Bulk Storage Share,
      path: /mnt/storage,
      browseable: yes,
      read_only: no,
      guest_ok: yes,
    }

filesharing_samba_users:
  - { name: '{{ main_username }}', password: '{{ secrets_main_sambapw }}' }

# assumes install of oh-my-zsh and powerlevel10K prompt
zsh_user_configs:
  - username: '{{ main_username }}'
    antigen_bundles:
      - git
