---
myhostname: mummy

# grog.package - extra packages for this group/server
package_list_group:
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: smartmontools
  - name: cryptsetup
  - name: zfsutils-linux

# geerlingguy-pip
pip_install_packages:
  - name: docker

# ironicbadger-snapraid
snapraid_config_excludes:
  - '*.unrecoverable'
  - '/tmp/'
  - '/lost+found/'
  - 'downloads/'
  - '*.!sync'
  - '.AppleDouble'
  - '._AppleDouble'
  - '.DS_Store'
  - '._.DS_Store'
  - '.Thumbs.db'
  - '.fseventsd'
  - '.Spotlight-V100'
  - '.TemporaryItems'
  - '.Trashes'
  - '.AppleDB'

# initial mapping:
# 2T SAS  /dev/disk/by-id/scsi-35000cca06d15906c -> ../../sdb
# 2T SAS  /dev/disk/by-id/scsi-35000cca06d159054 -> ../../sdc
# 2T SAS  /dev/disk/by-id/scsi-35000cca06d11fcb8 -> ../../sdd
# 2T SAS  /dev/disk/by-id/scsi-35000cca06d12ac50 -> ../../sde
# 4T SATA /dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K4YFTS7L -> ../../sdg

drivesetup_drives:
  - device: /dev/disk/by-id/scsi-35000cca06d15906c
    name: dat1
    path: /mnt/dat1
    label: DAT1
    keyfile: '{{ disckey }}'
    mkfs_type: ext4
  - device: /dev/disk/by-id/scsi-35000cca06d159054
    name: dat2
    path: /mnt/dat2
    label: DAT2
    keyfile: '{{ disckey }}'
    mkfs_type: ext4
  - device: /dev/disk/by-id/scsi-35000cca06d11fcb8
    name: dat3
    path: /mnt/dat3
    label: DAT3
    keyfile: '{{ disckey }}'
    mkfs_type: ext4
  - device: /dev/disk/by-id/scsi-35000cca06d12ac50
    name: dat4
    path: /mnt/dat4
    label: DAT4
    keyfile: '{{ disckey }}'
    mkfs_type: ext4
  # - device: /dev/disk/by-id/ata-WDC_WD40EFRX-68N32N0_WD-WCC7K4YFTS7L
  #   name: par1
  #   path: /mnt/par1
  #   label: PAR1
  #   keyfile: '{{ disckey }}'
  #   mkfs_type: ext4

# shutterkurt-mergerfs role
# insert mergerfs item into fstab
mergerfs_fstab_info:
  - {
      # source: '/mnt/dat*:/mnt/tank/docs-shared:/mnt/tank/photo-wip',
      source: '/mnt/dat*',
      mountpoint: '/mnt/storage',
      fs: fuse.mergerfs,
      opts: 'defaults,nonempty,allow_other,use_ino,moveonenospc=true,category.create=epmfs,cache.files=off,dropcacheonclose=true,minfreespace=20G,fsname=mergerfs',
    }
# install or not the extra python tools with mergerfs
mergerfs_tools_install: true

# shutterkurt-filesharing
filesharing_shares:
  - {
      name: storage,
      comment: Bulk Storage Share,
      path: /mnt/storage,
      browseable: yes,
      read_only: no,
      guest_ok: yes,
    }

filesharing_samba_users:
  - { name: '{{ main_username }}', password: '{{ secrets_main_sambapw }}' }

# shutterkurt-zsh
# assumes install of oh-my-zsh and powerlevel10K prompt
# zsh-syntax-highlighting needs to be last! (must be last to hook into cmd line)
zsh_user_configs:
  - username: '{{ main_username }}'
    antigen_bundles:
      - git
      - zsh-users/zsh-syntax-highlighting

#TODO: figure out what to move to the higher level all.yaml

# ironicbadger.docker_compose_generator
appdata_path: /mnt/storage/appdata

# shutterkurt-services
services_stacks_dir: 'compose/stack*.yaml'
