---
- name: Dump
  hosts: all
  gather_facts: false
  tasks:
    - name: Facts
      ansible.builtin.setup:
    - name: Dump
      delegate_to: localhost
      # run_once: true
      become: false
      ansible.builtin.copy:
        content: '{{ hostvars[inventory_hostname] | to_nice_json }}'
        dest: setup-dump.json
        mode: 0755
