# installs packages on target
# why not 'package' ?
# grog.package has 3 package list vars that are merged
# - makes it a little more flexable
- src: grog.package

# sets up various things to help with security on target
# - install sw to monitor bad ssh access (fail2ban)
# - configure ssh (disable root, only key-based, custom port)
# - automatic updates (if enabled)
- src: geerlingguy.security
# installs ntp on linux setting timezone, pool area
# ntp_area:'North America'
# ntp_timezone:America/New_York
# ntp_manage_config: true
# - src: geerlingguy.ntp
# ubuntu by default uses timesyncd already installed by default
# probably ok for right now

# installs docker, docker compose on target; adds system users to docker group
# - src: geerlingguy.docker

# perhaps add the geerlingguy.pip role
# installs pip3 (python3-pip), and list of pip packages to install
# can install into virtualenv as well

# take a github username and create system account with same
# then add all the public keys associated with the github account to the
# user's 'authorized_keys'
# copies from {{github_url}}/{{item.name}}.keys
# - src: geerlingguy.github-users

# installs and configures hddtemp for debian
# - src: ironicbadger.ansible_role_hddtemp

# not sure I'll use - look for zsh, oh-my-zsh, etc
# https://github.com/gantsign/ansible-role-oh-my-zsh
#or https://galaxy.ansible.com/gantsign/antigen
# - src: ironicbadger.ansible_role_bash_aliases

# builds from docker, installs, configures snapraid
# and either installs cron job or snapraidrunner for periodic scrubs
# - src: ironicbadger.ansible_role_snapraid

# role to manage users on a system - there must be a built in role for this!
# not sure I even need - other than copying ssh keys?
# - src: ironicbadger.ansible_users

# install, configure, manage telegraf
# - src: rossmcdonald.telegraf

# not now
# - src: ironicbadger.ansible_role_proxmox_nag_removal

# use builtin instead?  why this??
# builtin: docker_container or docker_compose ??
# - src: ironicbadger.ansible_role_docker_compose_generator
#
