---
- hosts: all
  tasks: # THINK: consider using pre_tasks / post_tasks instead as tasks is run after roles!
    - name: remove ubuntu motd spam
      become: true
      file:
        path: '/etc/update-motd.d/{{ item }}'
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 10-help-text
      when: ansible_distribution == 'Ubuntu'
- hosts: mummy
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: shutterkurt-mummy
    - role: shutterkurt-mergerfs
    - role: shutterkurt-filesharing
    - role: shutterkurt-zsh
