---
- name: Remove MOTD SPAM
  hosts: all
  tasks: # THINK: consider using pre_tasks / post_tasks instead as tasks is run after roles!
    - name: Remove ubuntu motd spam
      become: true
      ansible.builtin.file:
        path: '/etc/update-motd.d/{{ item }}'
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 10-help-text
      when: ansible_distribution == 'Ubuntu'

- name: Setup Drives for Mummy
  hosts: mummy
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: shutterkurt-drivesetup
    - role: shutterkurt-mergerfs
  tags:
    - drivesetup

- name: Setup Mummy
  hosts: mummy
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: shutterkurt-filesharing
    - role: shutterkurt-zsh
    - role: geerlingguy.security
    - role: ironicbadger.hddtemp
    - role: shutterkurt-bat
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: shutterkurt-services
    - role: ironicbadger.snapraid
      tags: testing
    - role: shutterkurt-mummy

- name: Setup gypsy
  hosts: gypsy
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    # - role: geerlingguy.security
    # - role: geerlingguy.pip

- name: Setup HA
  hosts: homeassistant
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: shutterkurt-zsh
    - role: geerlingguy.security
    # - role: ironicbadger.hddtemp
    - role: shutterkurt-bat
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: shutterkurt-ha
