---
- name: Update All
  hosts: all
  tasks:
    # - name: import keys from github  # FIXME: update for my keys
    #   authorized_key:
    #     user: "{{ ansible_user | default('yourname') }}"
    #     state: present
    #     key: https://github.com/ironicbadger.keys
    #
    # keeping update separate so can see it :)
    # FIXME: update so work with arch - at least put in only if ubuntu
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Update all packages
      ansible.builtin.apt:
        name: '*'
        state: latest
