---
bat_arch_map:
  x86_64: amd64
  # i386: i386
  # aarch64: arm64
  armv7l: armhf
  armv6l: armhf
bat_arch: '{{ bat_arch_map[ansible_userspace_architecture | default(ansible_architecture) ] }}'
bat_pkg_prefix: 'bat_'
bat_pkg_suffix: '_{{ bat_arch }}.deb'
