---
- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure Samba-related packages are installed
  apt:
    name:
      - samba
      - samba-common
    state: present

- name: Ensure Samba is running and starts on boot
  service:
    name: smbd
    state: started
    enabled: true

# create an explicit samba guest user -
# the default 'nobody' user is not part of the 'users' group
# so can't see inside a directory created by a linux user
# since shares have group sticky bit is set so group is overrided to 'users'
# could change the nobody user but created a new user to be explicit
# see conf file template - the guest account is set in the [global] section
- name: Ensure a Samba Guest account is created
  ansible.builtin.user:
    name: sambaguest
    group: users
    create_home: no
    state: present

- name: install samba config
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
  notify:
    - restart samba service

# use the group sticky bit on shares to make the dir/files accessable by
# other users in the 'users' group - but not others
- name: ensure shares (top level directories) have valid permissions
  ansible.builtin.file:
    path: '{{ item.path }}'
    owner: nobody
    group: users
    mode: 02770
  with_items: '{{ filesharing_shares }}'
  loop_control:
    label: '{{ item.path }}'
  notify:
    - restart samba service

- name: ensure that the samba users are in the users group
  ansible.builtin.user:
    name: '{{ item.name }}'
    groups: users
    append: yes
  with_items: '{{ filesharing_samba_users }}'
  loop_control:
    label: '{{ item.name }}'
  no_log: true # so password isn't logged!
  notify:
    - restart samba service
# set user password within samba to access user share
# - name: Configure Samba users.
#   shell: >
#     (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
#     || (echo '{{ item.password }}'; echo '{{ item.password }}')
#     | smbpasswd -s -a {{ item.username }}
#   register: smbpasswd
#   changed_when: "'Added user' in smbpasswd.stdout"
#   with_items: '{{ filesharing_samba_users }}'
#   loop_control:
#     label: '{{ item.username }}'
#   when: "{{ filesharing_enable_homes }}"
#   no_log: true # so password isn't logged!
