- name: Copy load keys service file
  copy:
    src: zfs-load-key.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Ensure load key service is enabled at boot
  ansible.builtin.systemd:
    name: zfs-load-key.service
    enabled: yes
#
#
#  FIXME: copy over the zfs override for docker
# https://serverfault.com/questions/904421/docker-service-starts-before-zfs
# i.e. force docker not to start unless zfs is started
# fixes possible race condition between zfs mounting drives
# and docker trying to use them
# - name: override docker service for zfs dependencies
#   include: docker-zfs-override.yml
#   when: docker_zfs_override
