---
- name: install mergerfs
  include: install.yml
  when: mergerfs_install

- name: Ensure /mnt points are created
  file:
    dest: '{{ item.mountpoint }}'
    state: directory
    owner: nobody
    group: users
    mode: 0770
  with_items: '{{ mergerfs_fstab_info }}'
  loop_control:
    label: '{{ item.mountpoint }}'

- name: mount mergerfs array
  mount:
    path: '{{ item.mountpoint }}'
    src: '{{ item.source }}'
    opts: '{{ item.opts }}'
    fstype: '{{ item.fs }}'
    # 'mounted' to auto mount
    # 'present' will only change fstab but not mount
    state: mounted
  loop_control:
    label: '{{ item.mountpoint }}'
  with_items:
    - '{{ mergerfs_fstab_info }}'
